language: node_js
node_js:
  - "stable"
services:
  - postgresql

before_script:
  - npm install -g mocha
  - npm install -g nyc
  - npm install -g sequelize-cli
script:
  - npm test

after_success: npm run coverage